CREATE TABLE IF NOT EXISTS roles (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL UNIQUE,
    builtin BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id    BIGINT      NOT NULL REFERENCES roles (id),
    permission VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS shares (
    token         VARCHAR(255) NOT NULL PRIMARY KEY,
    type          VARCHAR(50)  NOT NULL,
    resource_type VARCHAR(50)  NOT NULL,
    space_id      VARCHAR(255) NOT NULL,
    resource_path VARCHAR(255),
    label         VARCHAR(255),
    expires_at    TIMESTAMP,
    created_by    VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);
